# Generated by Django 3.2.6 on 2021-08-18 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantiry',
            new_name='quantity',
        ),
    ]
